#Template to deploy a cluster with region and instance type specified
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ekscluster
  region: us-west-1

nodeGroups:
  - name: eksgroup
    instanceType: t3.micro
    desiredCapacity: 2

managedNodeGroups:
  - name: eksmananaged
    instanceType: t3.micro
    minsize: 1
    maxsize: 1
    desiredCapacity: 2